// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FiledownloadTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void filedownload() {
    driver.get("https://spring.io/");
    driver.manage().window().setSize(new Dimension(1875, 1042));
    driver.findElement(By.name("&lpos=apps_scodevmw : 38")).click();
    driver.findElement(By.linkText("start.spring.io")).click();
    driver.findElement(By.id("input-group")).click();
    driver.findElement(By.id("input-group")).click();
    driver.findElement(By.id("input-group")).click();
    {
      WebElement element = driver.findElement(By.id("input-group"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("input-group")).sendKeys("com.uiu");
    driver.findElement(By.id("input-artifact")).click();
    driver.findElement(By.id("input-artifact")).click();
    {
      WebElement element = driver.findElement(By.id("input-artifact"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("input-artifact")).sendKeys("app");
    driver.findElement(By.id("input-description")).click();
    driver.findElement(By.id("input-description")).sendKeys("Demo APP For selenium Testing");
    driver.findElement(By.cssSelector("#explore-dependencies > .button-content > span:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".selected > strong")).click();
    driver.findElement(By.cssSelector("#explore-dependencies > .button-content > span:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".selected > span")).click();
    driver.findElement(By.cssSelector(".desktop-only:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".selected")).click();
    driver.findElement(By.cssSelector("#explore-dependencies > .button-content > span:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".selected > span")).click();
    driver.findElement(By.cssSelector(".desktop-only:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".selected > strong")).click();
    driver.findElement(By.cssSelector("#explore-dependencies > .button-content > span:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".selected")).click();
    driver.findElement(By.cssSelector(".fade-enter-done:nth-child(3) .icon-remove")).click();
    driver.findElement(By.cssSelector(".button-content > .icon-moon > path")).click();
    driver.findElement(By.cssSelector(".button-content > .icon-sun > path")).click();
    driver.findElement(By.cssSelector("#generate-project > .button-content > span:nth-child(1)")).click();
  }
}
