# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFiledownload():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_filedownload(self):
    self.driver.get("https://spring.io/")
    self.driver.set_window_size(1875, 1042)
    self.driver.find_element(By.NAME, "&lpos=apps_scodevmw : 38").click()
    self.driver.find_element(By.LINK_TEXT, "start.spring.io").click()
    self.driver.find_element(By.ID, "input-group").click()
    self.driver.find_element(By.ID, "input-group").click()
    self.driver.find_element(By.ID, "input-group").click()
    element = self.driver.find_element(By.ID, "input-group")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "input-group").send_keys("com.uiu")
    self.driver.find_element(By.ID, "input-artifact").click()
    self.driver.find_element(By.ID, "input-artifact").click()
    element = self.driver.find_element(By.ID, "input-artifact")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "input-artifact").send_keys("app")
    self.driver.find_element(By.ID, "input-description").click()
    self.driver.find_element(By.ID, "input-description").send_keys("Demo APP For selenium Testing")
    self.driver.find_element(By.CSS_SELECTOR, "#explore-dependencies > .button-content > span:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".selected > strong").click()
    self.driver.find_element(By.CSS_SELECTOR, "#explore-dependencies > .button-content > span:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".selected > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".desktop-only:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".selected").click()
    self.driver.find_element(By.CSS_SELECTOR, "#explore-dependencies > .button-content > span:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".selected > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".desktop-only:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".selected > strong").click()
    self.driver.find_element(By.CSS_SELECTOR, "#explore-dependencies > .button-content > span:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".selected").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fade-enter-done:nth-child(3) .icon-remove").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button-content > .icon-moon > path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button-content > .icon-sun > path").click()
    self.driver.find_element(By.CSS_SELECTOR, "#generate-project > .button-content > span:nth-child(1)").click()
  
